title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/AI conference deadlines
author: Michael Luo

domain: ""
baseurl: "/ai-deadlines"

twitter_username: bguedj
twitter_hashtag: machinelearning
github_username: ltz0120
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-81430854-1

include: ['_pages']
