title: AI/ML Conference Deadlines
description: Countdowns to international AI/ML conferences deadlines
author: Benjamin Guedj

domain: ""
baseurl: "/ai-deadlines"

twitter_username: bguedj
twitter_hashtag: machinelearning
github_username: bguedj
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-81430854-1

include: ['_pages']